name: Build & Push Backend + Frontend To ECR

on:
  push:
    branches: ["main"]

jobs:
  Build-Push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login To Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # -----------------------------
    # Backend Image Build & Push
    # -----------------------------
    - name: Build Docker Image (Backend)
      run: |
        docker build \
          -f backend/Dockerfile \
          -t ${{ secrets.ECR_REPOSITORY_BACKEND }}:latest \
          ./backend

    - name: Tag Backend Image
      run: |
        docker tag \
          ${{ secrets.ECR_REPOSITORY_BACKEND }}:latest \
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_BACKEND }}:latest

    - name: Push Backend Image
      run: |
        docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_BACKEND }}:latest

    # -----------------------------
    # Frontend Image Build & Push
    # -----------------------------
    - name: Build Docker Image (Frontend)
      run: |
        docker build \
          -f frontend/Dockerfile \
          -t ${{ secrets.ECR_REPOSITORY_FRONTEND }}:latest \
          ./frontend

    - name: Tag Frontend Image
      run: |
        docker tag \
          ${{ secrets.ECR_REPOSITORY_FRONTEND }}:latest \
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_FRONTEND }}:latest

    - name: Push Frontend Image
      run: |
        docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_FRONTEND }}:latest